# Form implementation generated from reading ui file '/Users/juliusarolovitch/Desktop/Makey Makey/test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(264, 244)
        Form.setStyleSheet("background-color: rgb(215, 215, 215)")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(40, 25, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.timer = QtWidgets.QLabel(parent=Form)
        self.timer.setGeometry(QtCore.QRect(40, 50, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.timer.setFont(font)
        self.timer.setStyleSheet("background-color: rgb(30, 30, 30);\n"
                                 "color: white;\n"
                                 "border-radius: 4px;\n"
                                 "")
        self.timer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timer.setObjectName("timer")
        self.the_button = QtWidgets.QPushButton(parent=Form)
        self.the_button.setGeometry(QtCore.QRect(40, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.the_button.setFont(font)
        self.the_button.setStyleSheet("background-color: rgb(44, 136, 0);\n"
                                      "color: white;\n"
                                      "border-radius: 4px;\n"
                                      "")
        self.the_button.setObjectName("the_button")
        self.the_quit = QtWidgets.QPushButton(parent=Form)
        self.the_quit.setGeometry(QtCore.QRect(40, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.the_quit.setFont(font)
        self.the_quit.setStyleSheet("background-color: rgb(136, 4, 0);\n"
                                    "color: white;\n"
                                    "border-radius: 4px;\n"
                                    "")
        self.the_quit.setObjectName("the_quit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Hand Washing Monitor"))
        self.timer.setText(_translate("Form", "0.00"))
        self.the_button.setText(_translate("Form", "Start"))
        self.the_quit.setText(_translate("Form", "Quit"))
